# WRITE
CLEAR_STATUS = "*CLS"
RESET = "*RST"
SYSTEM_REMOTE = "SYST:REM"
TRIGGER = "TRIG:IMM"
FUNC_CURR = "FUNC CURR"
ALL_INPUTS_ON = "INP:ALL 1"
ALL_INPUTS_OFF = "INP:ALL 0"
INPUT_ON = "INP 1"
INPUT_OFF = "INP 0"
SELECT_CHANNEL = "CHAN "
SET_CURR = "CURR "

# QUERY
INST_ID = "*IDN?"
FETCH_VOLT = "FETC:VOLT?"
FETCH_CURR = "FETC:CURR?"
FETCH_POW = "FETC:POW?"
